const { withProjectBuildGradle } = require('@expo/config-plugins');

// LiteRT-LM 0.11.0 (needed for Gemma-4 int4 on the GPU) ships Kotlin 2.3 metadata,
// which the default project Kotlin (2.1) can't read. Bump the whole project to
// Kotlin 2.3.0 (the Expo root plugin explicitly supports kotlinVersion >= 2.3.0 and
// auto-selects a matching KSP). android/ is regenerated by prebuild, so we apply
// this as a config plugin for persistence.
const KOTLIN_VERSION = '2.3.0';

module.exports = function withKotlinVersion(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') return cfg;
    let src = cfg.modResults.contents;
    if (src.includes(`ext.kotlinVersion = "${KOTLIN_VERSION}"`)) return cfg;

    // Force the Kotlin Gradle plugin (compiler) version.
    src = src.replace(
      "classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')\n  }",
      "classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')\n  }\n" +
        '  configurations.classpath {\n' +
        '    resolutionStrategy.eachDependency {\n' +
        "      if (requested.group == 'org.jetbrains.kotlin' && requested.name == 'kotlin-gradle-plugin') {\n" +
        `        useVersion '${KOTLIN_VERSION}'\n` +
        '      }\n' +
        '    }\n' +
        '  }'
    );

    // Set the project-level kotlinVersion that the Expo root plugin reads.
    src = src.replace('\nallprojects {', `\next.kotlinVersion = "${KOTLIN_VERSION}"\n\nallprojects {`);

    cfg.modResults.contents = src;
    return cfg;
  });
};
